name: Build and Run Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t onione:latest .

      # Run the Docker image
      - name: Run Docker container
        run: |
          docker run -it onione:latest



