name: Run ls -la Command

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: List Files and Directories
      run: ls -la
