name: Build and Run Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Set up Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t onione:latest .

      # Run the Docker container (non-interactive)
      - name: Run Docker container
        run: |
          docker run onione:latest

      # Check Docker container logs (if any issues)
      - name: Check Docker logs
        run: |
          docker ps -a
